name: Daily Update and Deployment

on:
  schedule:
    - cron: '0 12 * * *'  # 5 AM PST
  push:
    branches:
      - main

jobs:
  render_and_deploy:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up R environment
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    # Install system dependencies (like `libcurl` for GitHub)
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

    # Install R dependencies using renv
    - name: Set up renv and install dependencies
      run: |
        install.packages("renv")
        renv::restore()  # Restore the dependencies based on the renv.lock file

    # Run R script to render the report
    - name: Render the report
      run: |
        Rscript -e "Inseasonfor::render_page_fun()"

    # Commit the updated .csv files to GitHub (if any changes)
    - name: Commit CSV files if changed
      run: |
        git config --global user.email "mark.sorel@dfw.wa.gov"
        git config --global user.name "marksorel8"
        git add inst/data-cache/*.csv
        git diff --quiet || git commit -m "Update CSV files" && git push

    # Deploy the site to gh-pages branch
    - name: Deploy to gh-pages
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        cp inst/Rmarkdown/site/index.html .  # Copy the rendered HTML
        git add index.html
        git commit -m "Deploy updated report to gh-pages"
        git push origin gh-pages
